# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joswlv
# brief-intro:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joswlv.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
# twitter_username: gaohaoyang126
facebook_username: wsj7923
github_username:  joswlv
email: wh7923@gmail.com
# weibo_username: 3115521wh
# zhihu_username:
# linkedIn_username:
# dribbble_username:

description_footer:

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname: #hygblog
disqus_shortname: joswlv

google_analytics_id: UA-83868242-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
